
additional info: https://github.com/lukebarousse/Python_Data_Analytics_Course/blob/main/1_Basics/22_NumPy.ipynb

In [1]:
# create a list of a 1,000,000 salary ranging from 50k to 150k
import random

salary = [random.randint(50000,150000) for sal in range(1000000)] # list comprehension

In [2]:
salary

[109681,
 149432,
 105921,
 57409,
 114832,
 105091,
 70072,
 137067,
 63996,
 129498,
 142689,
 93609,
 121884,
 80935,
 51103,
 55501,
 126894,
 55904,
 80727,
 143197,
 132336,
 142678,
 144007,
 57004,
 95569,
 90355,
 132650,
 62325,
 75800,
 60339,
 93901,
 127136,
 112863,
 63356,
 61933,
 85658,
 108542,
 62568,
 50032,
 112953,
 136789,
 109606,
 63749,
 66980,
 82907,
 61193,
 108275,
 84566,
 85057,
 127698,
 109593,
 97179,
 114523,
 115299,
 139887,
 126325,
 73476,
 145616,
 57927,
 135167,
 108070,
 111051,
 97748,
 142281,
 130818,
 106986,
 99687,
 120333,
 79175,
 66979,
 112430,
 122367,
 130770,
 84641,
 85310,
 76424,
 70916,
 98588,
 129795,
 53611,
 136337,
 80777,
 52853,
 105064,
 134494,
 125856,
 79301,
 86327,
 91360,
 95074,
 60633,
 82571,
 107107,
 67080,
 64860,
 134454,
 138552,
 65038,
 147474,
 120878,
 68679,
 123831,
 141787,
 129139,
 61807,
 128620,
 122312,
 127526,
 106190,
 88776,
 144529,
 89507,
 141982,
 105634,
 111382,
 127709,
 51336,
 64

Clearly numpy is faster with the calculation

In [3]:
import statistics
import numpy as np

In [4]:
%%timeit

statistics.mean(salary)

The slowest run took 5.47 times longer than the fastest. This could mean that an intermediate result is being cached.
688 ms ± 374 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%%timeit

np.mean(salary)

156 ms ± 35.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


**NumPy**: Numerical Python, is foundational for numerical computing in Python.

`import numpy as np; np.array([1, 2, 3])`

In [9]:
my_array = np.array([ 62224,
 55692,
 83282,
 106358,
 140357,
 106253,
 149625])

In [10]:
my_array.mean()

100541.57142857143

In [22]:
job_title = np.array(['Data Analyst','Data Science', 'Data Engineer','Machine Learning Engineer','AI Engineer'])

base_salary = np.array([60000,80000,100000,120000,np.nan])

bonus_rate = np.array([.05,.1,.15,.08,np.nan])

In [25]:
total = base_salary * (1+bonus_rate) # can do computations betweeb arrays

In [14]:
total

array([ 63000.,  88000., 115000., 129600.])

In [27]:
np.nanmean(total)

98900.0

In [29]:
total.mean()

nan

In [38]:
my_array[0:2]

array([62224, 55692])

# NaN


- np.nan value is used in NumPy (and by extension, Pandas) to represent missing or undefined data
- Helpful because it:
- - Handles missing data.
- - Helps with computations since it won't return errors but instead return np.nan.
- - Help filter out or fill in missing data using other methods that we'll use often in the pandas library like `dropna()`, `fillna()`, `isna()`, or `notna()`.

In [34]:
type(None),type(np.nan)

(NoneType, float)

In [39]:
sal_nan = np.array([ 62224,
 np.nan,
 83282,
 106358,
 140357,
 106253,
 149625])

In [33]:
my_array[my_array > 0]  # bolean indexing

array([ 62224,  55692,  83282, 106358, 140357, 106253, 149625])

In [41]:
sal_nan[sal_nan < 100000] = np.nan
sal_nan

array([    nan,     nan,     nan, 106358., 140357., 106253., 149625.])

In [42]:
np.random.normal(100,500,sal_nan.size)

array([ -24.20114232,  416.85671589,  224.76899911,  610.07739056,
        178.55423886,   76.01258535, 1147.24704241])